# --- DÉCLARATION DES SERVICES --- 
services:
  
  # 1. Base de données PostgreSQL (Stockage des votes)
  db:
    image: postgres:15-alpine
    container_name: voting_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # Assure la persistance des données
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
    # Vérification de l'état de santé
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Donne le temps à la BDD de démarrer initialement
      
    restart: always
    networks:
      - app-network

  # 2. Base de données de mise en cache Redis (Queue de messages)
  redis:
    image: redis:6-alpine
    container_name: voting_redis
    
    # Vérification de l'état de santé
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      
    restart: always
    networks:
      - app-network

  # 3. Application Web de Vote (Python Flask)
  vote:
    build:
      context: ./voting-app
      dockerfile: ./vote/Dockerfile
    container_name: voting_app
    
    # Exposition du port : 5000 sur l'hôte -> 8080 dans le conteneur
    ports:
      - "5000:8080" 
      
    # Dépend de Redis
    depends_on:
      redis:
        condition: service_healthy 
        
    environment:
      OPTION_A: "Chats"
      OPTION_B: "Chiens"
    restart: on-failure
    networks:
      - app-network

  # 4. Service Worker (.NET Core)
  worker:
    build:
      context: ./voting-app
      dockerfile: ./worker/Dockerfile
    container_name: voting_worker
    
    # Dépend de Redis (lire) et de la BDD (écrire)
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
        
    restart: on-failure
    networks:
      - app-network

  # 5. Application Web de Résultats (Node.js)
  result:
    build:
      context: ./voting-app
      dockerfile: ./result/Dockerfile 
    container_name: voting_result
    
    # Exposition du port : 5001 sur l'hôte -> 8888 dans le conteneur
    ports:
      - "5001:8888" 
      
    # Dépend de la BDD (lire les résultats)
    depends_on:
      db:
        condition: service_healthy
        
    restart: on-failure
    networks:
      - app-network

# --- DÉCLARATION DES VOLUMES ---
volumes:
  # Volume nommé pour la persistance des données de PostgreSQL
  postgres-data:
    driver: local

# --- DÉCLARATION DES RÉSEAUX ---
networks:
  # Réseau interne pour la communication entre services
  app-network:
    driver: bridge